### ISSUE TITLE
Background Image Share by All Pages 

### ISSUE THREAD

**Issue by mubarakshow** [zero-to-mastery/mappypals#66]
The problem is in [Home.css](https://github.com/zero-to-mastery/mappypals/blob/master/src/pages/Home/Home.css) where we used id ```#root``` to assign the background image.
```css 
#root{
    background-image: url('../../pics/adult-backlit-beach.jpg');
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
```
This gives every page in the app the same background image which shouldn't be. Some pages might need a different background-image and some don't need it at all.
